runes_name = {
    12: 'PA',
    8: 'PM',
    31: 'Portée',
    28: 'Invocation',
    30: 'Dommages',
    41: '% Dommages d\'armes',
    71: '% Dommages distance',
    40: '% Dommages mêlée',
    93: '% Dommages aux sorts',
    108: '% Résistance distance',
    65: '% Résistance mêlée',
    11: 'Soins',
    29: '% Critique',
    125: 'Renvoi de dommage',
    50: 'Retrait PM',
    64: 'Retrait PA',
    39: 'Esquive PM',
    75: 'Esquive PA',
    63: '% Résistance Terre',
    17: '% Résistance Eau',
    34: '% Résistance Neutre',
    37: '% Résistance Feu',
    16: '% Résistance Air',
    48: 'Dommages Terre',
    27: 'Dommages Eau',
    49: 'Dommages Neutre',
    61: 'Dommages Feu',
    47: 'Dommages Air',
    38: 'Dommages Critiques',
    62: 'Dommages Poussée',
    112: 'Dommages Pièges',
    92: 'Arme de chasse',
    26: 'Tacle',
    59: 'Fuite',
    25: 'Prospection',
    10: 'Sagesse',
    106: 'Puissance Piège',
    32: 'Puissance',
    15: 'Résistances Terre',
    82: 'Résistances Eau',
    33: 'Résistances Neutre',
    14: 'Résistances Feu',
    60: 'Résistances Air',
    46: 'Résistances Critiques',
    70: 'Résistances Poussée',
    45: 'Force',
    13: 'Intelligence',
    22: 'Chance',
    36: 'Agilité',
    78: 'Pods',
    9: 'Vitalité',
    24: 'Initiative'
}
